### PR TITLE
vote: tier-cap as TiKV reviwer

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
+1 binding, congrats! Looks like there are many more to do to handle the TiKV disk full situation 🤣

**Review by sticnarf — APPROVED** [review]
LGTM. @tier-cap has done great job on improving the case when the disk is full and has shown a solid understanding of the raftstore.

**Pull request merged**
