### PR TITLE
Promote @niedhui to committer

### PR DESCRIPTION
**Pull request by breeswish**
@niedhui contributed more than 40 PRs in TiKV, mainly for the Coprocessor component: https://github.com/tikv/tikv/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aniedhui+

Besides implementing a lot of built-in functions, he has also implemented several important TiKV coprocessor features:

### Use the new codec for Coprocessor component

- https://github.com/tikv/tikv/pull/4454
- https://github.com/tikv/tikv/pull/5259
- https://github.com/tikv/tikv/pull/5323
- https://github.com/tikv/tikv/pull/5450
- https://github.com/tikv/tikv/pull/5496
- https://github.com/tikv/tikv/pull/5520

### Support row format v2

- https://github.com/tikv/tikv/pull/5725
- https://github.com/tikv/tikv/pull/6132

He has revealed great understanding for the Coprocessor module according to these PRs. He has also [helped reviewed many community PRs](https://github.com/tikv/tikv/pulls?utf8=%E2%9C%93&q=commenter%3Aniedhui). For this reason, I nominate to promote him as a committer.

### CODE REVIEW

**Comment by dcalvin** [comment]
Reminder - this requires supermajority votes from TiKV Maintainers. @breeswish

**Comment by Hoverbear** [comment]
Yay! Go @niedhui :) You are amazing!

**Comment by lonng** [comment]
Congratulation @niedhui

**Comment by niedhui** [comment]
It is such an honor for me and thanks for your help in the past, I'm really looking forward to contributing more to the TiKV project.

**Comment by winkyao** [comment]
LGTM

**Pull request merged**
