### PR TITLE
vote binshi-bing as PD committer

### PR DESCRIPTION
**Pull request by lhy1024**

### CODE REVIEW

**Review by binshi-bing — APPROVED** [review]
:)

**Review by rleungx — APPROVED** [review]
Congrats!

**Review by disksing — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Comment by lhy1024** [comment]
@nolouch @rleungx plz merge it

**Comment by binshi-bing** [comment]
Thanks @lhy1024 @rleungx @disksing @JmPotato @rleungx!

**Comment by nolouch** [comment]
Congratulations！

**Pull request merged**
