### PR TITLE
vote: pingyu as TiKV committer

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com> [Rendered](https://github.com/iosmanthus/community/blob/prompt-pingyu-as-committer/votes/0178-pingyu-as-tikv-committer.md)

Proposal

[@pingyu](https://github.com/pingyu) has been working on tikv/tikv for 8 months. He has continuously contributed to storage and RawKV related components (api_version, causal_ts, etc.). His contributions are listed:

[Authored pull requests](https://github.com/tikv/tikv/pulls?q=is%3Apr+author%3Apingyu+is%3Amerged)
[Reviewed pull requests](https://github.com/tikv/tikv/pulls?q=is%3Apr+reviewed-by%3Apingyu)
I (@iosmanthus) hereby nominate @pingyu as TiKV Committer and call for a vote.

### CODE REVIEW

**Review by andylokandy — APPROVED** [review]
+1

**Review by BusyJay — APPROVED** [review]
Thank you for your contributions!

**Comment by sunxiaoguang** [comment]
+1

Thanks for your contribution!

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
