### PR TITLE
Make zyguan reviewer for sig-transaction

### PR DESCRIPTION
**Pull request by cfzjywxk**
Zyguan has raised many issues(50+) for TiDB transaction and execution layer and made great contributions to the transaction test utilities like [jepsen](https://github.com/PingCAP-QE/jepsen) tests, tipocket, [tp-test](https://github.com/zyguan/go-randgen/tree/tp-test/tp-test), etc.
So we would like to promote him to the transaction sig reviewer.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@andylokandy @youjiali1995 @sticnarf @nrc PTAL

**Review by sticnarf — APPROVED** [review]
LGTM!

**Review by youjiali1995 — APPROVED** [review]
LGTM

**Pull request merged**
