### PR TITLE
Revert "vote: gozssky as TiKV reviwer"

### PR DESCRIPTION
**Pull request by tisonkun**
Reverts tikv/community#141

violate governance rule

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
(not important) I think it should be "violate" instead of "violet"?👀

**Comment by tisonkun** [comment]
@JaySon-Huang yes. Updated.

**Comment by skyzh** [comment]
This seems to be the first time that our rules are violated. After this accident has happened, I believe for now all of the community members should have been acknowledged the promotion rules.

So as for this PR, to simplify the process, I suggest that we simply wait for 3 days. If there are no vetoes and this promotion meets the requirements, we may close this PR and assume #141 valid.

After all, thanks for @gozssky 's contribution!

+1 (binding)

**Comment by tisonkun** [comment]
@skyzh thanks for your suggestion. I highly respect @gozssky's contribution, but hesitated to make a special case that 

> close this PR and assume #141 valid.

or something. If we allow this time, what about the next time we continue "assume an invalid vote passed". We should create as less exceptions as possible.

It's find to the nominator proposes once more. We don't have to rush things or chasing just in place convenience, but keep the rules we wrote down.

**Comment by tisonkun** [comment]
@skyzh thanks for your suggestion. I highly respect @gozssky's contribution, but hesitated to make a special case that 

> close this PR and assume #141 valid.

or something. If we allow this time, what about the next time we continue "assume an invalid vote passed". We should create as less exceptions as possible.

It's find to the nominator proposes once more. We don't have to rush things or chasing just in place convenience, but keep the rules we wrote down.

**Comment by tisonkun** [comment]
@skyzh thanks for your suggestion. I highly respect @gozssky's contribution, but hesitated to make a special case that 

> close this PR and assume #141 valid.

or something. If we allow this time, what about the next time we continue "assume an invalid vote passed". We should create as less exceptions as possible.

It's find to the nominator proposes once more. We don't have to rush things or chasing just in place convenience, but keep the rules we wrote down.

**Comment by skyzh** [comment]
Looks good to me. We could go over the process again.

**Pull request merged**
