### PR TITLE
vote: accept TiKV Dev Guide

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

/cc @tikv/maintainers

### CODE REVIEW

**Comment by tisonkun** [comment]
/hold

At least open util 2022-02-24 0:00:00 +0800.

**Review by BusyJay — APPROVED** [review]
Thanks!

**Comment by tisonkun** [comment]
@BusyJay @skyzh @breeswish @andylokandy we may still wait for another reviewer :)

**Review by skyzh — APPROVED** [review]
+1 for this. Hope more developers can learn from it, and contribute to this project!

**Comment by andylokandy** [comment]
+1 really looking forward to it

**Review by andylokandy — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your reviews! I'll conclude this proposal and transfer the repo later today.

**Pull request merged**
