### PR TITLE
nominate LykxSassinator as tikv committer

### PR DESCRIPTION
**Pull request by glorv**
@LykxSassinator

### CODE REVIEW

**Comment by glorv** [comment]
@zhangjinpeng87 @tonyxuqqi @overvenus @Connor1996 PTAL

**Review by zhangjinpeng87 — APPROVED** [review]
+1, LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
/cc @nolouch 
PTAL

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
LGTM

**Pull request merged**
