### PR TITLE
Promote committer JmPotato as committer in sig-scheduling

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: Song Gao <disxiaofei@163.com>

1. He has filed more than [50+ prs](https://github.com/tikv/pd/issues?q=is%3Apr+author%3AJmPotato+is%3Aclosed) 
2. He participated in the design of local tso and realized it which is a challenging task and he did it quite well.

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by JmPotato** [comment]
@tikv/maintainers PTAL, thx!

**Review by BusyJay — APPROVED** [review]
Congrat!

**Comment by JmPotato** [comment]
@tikv/maintainers One more LGTM needed, PTAL, thx!

**Review by disksing — APPROVED** [review]

**Pull request merged**
