### PR TITLE
Proposal: move `etcd-client` to tikv

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>

Opened a vote for add a fork of `etcd-v3/etcd-client` to TiKV org.

### CODE REVIEW

**Comment by YuJuncen** [comment]
/cc @BusyJay @overvenus @hicqu 
PTAL, thanks~

**Comment by BusyJay** [comment]
Why do you think tikv community is better than pingcap to maintain the repository?

**Comment by YuJuncen** [comment]
> Why do you think tikv community is better than pingcap to maintain the repository?

Because only `tikv` directly requires this?

`kvproto` infects both TiDB and TiKV side, so make it in `pingcap` would be a good choice, but for the `etcd-client` case, only TiKV side requires this module, maintaining it at `pingcap` would be a little strange.

**Comment by nolouch** [comment]
Why is there a fork?

**Comment by YuJuncen** [comment]
> Why is there a fork?

Generally, we need to expose some internal config of that library.

In a long term, we may port it to `grpc-rs` (now `tonic`).

**Comment by YuJuncen** [comment]
We haven't get consensus in a long time, and for now, this repo has been in the `pingcap` org and being suitable for maintaining. 

Let's suspend moving it to `tikv` until necessary.

**Comment by BusyJay** [comment]
@nolouch If PD can be embed into TiKV, we don't need etcd client at all. 😉

**Pull request closed without merging**
