### PR TITLE
promote Ning Lin to a committer

### PR DESCRIPTION
**Pull request by hicqu**
Ning Lin (@NingLin-P) has done some fantastic works about
joint-consensus. Here is a PR list:

* https://github.com/tikv/raft-rs/pull/375
* https://github.com/tikv/raft-rs/pull/346
* https://github.com/tikv/tikv/pull/8665
* https://github.com/tikv/tikv/pull/8477
* https://github.com/tikv/tikv/pull/8401
* https://github.com/tikv/tikv/pull/8081
* https://github.com/tikv/tikv/pull/7955
* https://github.com/tikv/tikv/pull/7697

Based on this, we promote him to a committer of Raft-sig.
Congratulations!

Signed-off-by: qupeng <qupeng@pingcap.com>

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]
Congrats!

**Review by winkyao — APPROVED** [review]
LGTM

**Comment by Rustin-Liu** [comment]
@winkyao, this PR is waiting for @hicqu to migrate membership.md to a JSON file. So cloud you please `/lgtm cancel`?

**Comment by Rustin-Liu** [comment]
ping~ @hicqu

**Comment by hi-rustin** [comment]
/cc @tikv/maintainers 

PTAL~ Thanks!

**Pull request merged**
